name: ems
description: Globalland Employee Management System

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^6.0.3
  auto_route_generator: ^6.0.0
  google_fonts: ^4.0.3
  provider: ^6.0.5
  animated_notch_bottom_bar: ^0.0.6
  lottie: ^2.3.1
  flutter_svg: ^1.1.6
  http: ^0.13.5
  shared_preferences: ^2.0.13
  flutter_device_type: ^0.4.0
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/map_style.txt
